baseURL = 'https://NirvanaCeleste.github.io/'
locale = 'zh-cn'
title = "NirvanaCeleste's Blog"
theme = 'blowfish'

[params]
  mainSections = ['acm', 'omori']
  enableSidebar = true
  enableSearch = true
  math = true

[menu]
  [[menu.main]]
    name = '🏠 主页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '💻 ACM 题解'
    url = '/acm/'
    weight = 2
  [[menu.main]]
    name = '🎮 OMORI 模组'
    url = '/omori/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]