baseURL = 'https://NirvanaCeleste.github.io/'
languageCode = 'zh-cn'
title = 'Nirvana Celeste Space'
theme = 'blowfish'

[params]
  mainSections = ['acm', 'omori']
  enableSidebar = true
  enableSearch = true

[menu]
  [[menu.main]]
    name = '主页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'ACM 题解'
    url = '/acm/'
    weight = 2
  [[menu.main]]
    name = 'OMORI 模组'
    url = '/omori/'
    weight = 3