baseURL = 'https://NirvanaCeleste.github.io/'
locale = 'zh-cn'
title = "NirvanaCeleste's Blog"
theme = 'blowfish'

[params]
  mainSections = ['acm', 'omori']
  enableSidebar = true
  enableSearch = true
  math = true

  [params.comments]
    enabled = true
    provider = "giscus" # 指定使用 giscus

[params.giscus]
    repo = "NirvanaCeleste/NirvanaCeleste.github.io"
    repoId = "R_kgDOTLg_BA"
    category = "General"
    categoryId = "DIC_kwDOTLg_BM4DAs4c"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "zh-CN"

[menu]
  [[menu.main]]
    name = '🏠 主页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '💻 ACM 题解'
    url = '/acm/'
    weight = 2
  [[menu.main]]
    name = '🎮 OMORI 模组'
    url = '/omori/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 这一行必须加上，否则 Giscus 的脚本会被安全机制删掉
    
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]

[module]
proxy = "https://goproxy.cn"